# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
