# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
        ('comentario', '0002_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='respuestade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='publicacion.Publicacion'),
        ),
    ]
