# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0003_comentario_respuestade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='respuestade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Publicacion'),
        ),
    ]
