# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0004_auto_20171216_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
